# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
null_vector.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vec6 = np.zeros(10)
vec6[4] = 1
vec6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vec7 = np.arange(10, 50)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.flip(vec7)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix9 = np.matrix(np.arange(0, 9).reshape(3, 3))
matrix9

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr10 = [1,2,0,0,4,0]
for i in range(0, len(arr10)):
  if arr10[i] == 0:
    print(f'index of 0 is {i}')

index of 0 is 2
index of 0 is 3
index of 0 is 5


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
m11 = np.identity(3)
print(m11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
m12 = np.random.rand(3, 3, 3)
m12

array([[[0.21183012, 0.22213746, 0.72737845],
        [0.23236055, 0.9247769 , 0.83900845],
        [0.50142864, 0.6473039 , 0.13259544]],

       [[0.48047214, 0.67989374, 0.24922649],
        [0.84189964, 0.6559716 , 0.06666794],
        [0.3636509 , 0.48889881, 0.28552625]],

       [[0.50650811, 0.26508433, 0.0148025 ],
        [0.17225591, 0.92323448, 0.19765063],
        [0.36352631, 0.74349388, 0.71552856]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a13 = np.random.rand(10, 10)
a13.max(), a13.min()

(0.9944042817916978, 0.013637216517897621)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
v14 = np.random.rand(30)
v14.mean()

0.4662785023058439

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a15 = np.ones((5,5))
a15[1:-1,1:-1] = 0
a15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
p16 = np.ones((4, 6)) # any array
a16 = np.zeros((p16.shape[0]+2,p16.shape[1]+2))
a16[1:-1,1:-1] = p16
a16

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
# print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)
0.1 * 3

nan
False
False
nan
False


0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
m18 = np.zeros([5, 5])
j=1;k=1
for i in range(1,5):
  m18[i,j-1] = k  
  j=j+1;k+=1
m18

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
a=np.ones((6,7,8))
m=0
for i in range(6):
  for j in range (7):
    for k in range(8):
      if(m==100):
       break
      m=m+1
print(i,j,k)

5 6 0


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
A = np.array([[[[[[[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]]]]]]])
x = np.tile(A,reps=4)
print(x)

[[[[[[[[0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]]]]]]]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a = np.random.rand(5,5)
min=np.min(a);max=np.max(a)
a=(a-min)/(max-min)
a

array([[0.70378923, 0.        , 0.45013278, 0.61677652, 0.95886393],
       [0.95560364, 0.21656909, 0.45075762, 0.27114698, 0.15484214],
       [0.17328101, 0.9521224 , 0.44859755, 1.        , 0.15310133],
       [0.71895598, 0.32292297, 0.14482976, 0.18127256, 0.45203103],
       [0.26207098, 0.60013072, 0.98960079, 0.01983946, 0.71574088]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
my_type = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
testt = np.array((1, 2, 3, 4), dtype=my_type)
print(my_type['R'])
testt

uint8


array((1, 2, 3, 4),
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.rand(5,3)
b=np.random.rand(3,2)
np.matmul(a,b)

array([[0.68898814, 0.30790427],
       [0.70742603, 0.14241248],
       [0.64618816, 0.14783246],
       [0.20299459, 0.06557609],
       [0.59860516, 0.28450268]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.random.randint(1,10,size=(20,))
for i in range(20):
  if (3<a[i])&(a[i]<8) :
    a[i]*=-1
a

array([ 8,  9,  1,  9,  8, -5, -5,  3, -7, -6, -7,  9,  8, -4,  3, -5, -4,
       -6,  8, -5])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
q = np.array([1, 2, 3])
q**q, 2 << q >> 2, q <- q, q/1/1

(array([ 1,  4, 27]),
 array([1, 2, 4]),
 array([False, False, False]),
 array([1., 2., 3.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Q = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Q)), Q))

[-10.   9.   9.   9.  -6.  -2.   2.   1.   8.  -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[3 4 5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2022-11-09'),
 numpy.datetime64('2022-11-10'),
 numpy.datetime64('2022-11-11'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
E = np.random.uniform(0,10,10)

print(E - E%1)
print(E // 1)
print(np.floor(E))
print(E.astype(int))
print(np.trunc(E))

[3. 8. 3. 7. 7. 1. 7. 1. 6. 4.]
[3. 8. 3. 7. 7. 1. 7. 1. 6. 4.]
[3. 8. 3. 7. 7. 1. 7. 1. 6. 4.]
[3 8 3 7 7 1 7 1 6 4]
[3. 8. 3. 7. 7. 1. 7. 1. 6. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
E = np.zeros((5,5))
E += np.arange(5)
print(E)

# without broadcasting
E = np.tile(np.arange(0, 5), (5,1))
print(E)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
E = np.fromiter(generate(),dtype=float,count=-1)
print(E)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
E = np.linspace(0,1,11,endpoint=False)[1:]
print(E)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
E = np.random.random(10)
E.sort()
print(E)

[7.93134796e-04 1.12240357e-01 2.85994167e-01 3.04996042e-01
 3.65945776e-01 3.90974254e-01 5.53486040e-01 6.90280195e-01
 7.89317520e-01 7.97895008e-01]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
E = np.arange(10)
np.add.reduce(E)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
M = np.zeros(10)
M.flags.writeable = False
# M[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
M = np.random.random((10,2))
X,Y = M[:,0], M[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.58968585 1.35609496 0.66894635 1.1247651  0.79218552 0.79086781
 1.39065235 0.92528291 1.3339456  0.47339477]
[1.53866278 0.77898908 0.92662694 1.00877551 0.42007465 0.82182819
 0.79356006 0.11166775 0.76702519 0.79298753]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
M = np.random.random(10)
M[M.argmax()] = 0
print(M)

[0.49935554 0.5130556  0.07442822 0.64048264 0.         0.74291504
 0.18297584 0.90393615 0.6097856  0.23597126]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
M = np.zeros((5,5), [('x',float),('y',float)])
M['x'], M['y'] = np.meshgrid(np.linspace(0,1,5), # Return coordinate matrices from coordinate vectors.
                             np.linspace(0,1,5))
print(M)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
M = np.zeros((40,40))
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
M = np.arange(100)
v = np.random.uniform(0,100) # Draw samples from a uniform distribution.
index = (np.abs(M-v)).argmin()
print(M[index])

36


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
M = np.zeros(10, [('position', 
                   [('x', float, 1), ('y', float, 1)]), 
                  ('color', [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(M)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
M = np.random.random((10,2))
X,Y = np.atleast_2d(M[:,0], M[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.30658754 0.46368859 0.77190557 0.50729138 0.78089193
  0.41603553 0.7971184  0.25369354 0.37586107]
 [0.30658754 0.         0.48068962 0.66391061 0.20523402 0.48281595
  0.11626895 0.53775429 0.37519423 0.34690168]
 [0.46368859 0.48068962 0.         0.34953764 0.54316413 0.87039105
  0.56891999 0.59914287 0.2174162  0.77407437]
 [0.77190557 0.66391061 0.34953764 0.         0.60927082 0.87770376
  0.70207638 0.43965676 0.55316127 1.00625733]
 [0.50729138 0.20523402 0.54316413 0.60927082 0.         0.32976035
  0.13558444 0.36124243 0.51479247 0.49544722]
 [0.78089193 0.48281595 0.87039105 0.87770376 0.32976035 0.
  0.36733825 0.49232911 0.83811286 0.60816199]
 [0.41603553 0.11626895 0.56891999 0.70207638 0.13558444 0.36733825
  0.         0.4963272  0.48655394 0.3600088 ]
 [0.7971184  0.53775429 0.59914287 0.43965676 0.36124243 0.49232911
  0.4963272  0.         0.69566886 0.85629922]
 [0.25369354 0.37519423 0.2174162  0.55316127 0.51479247 0.83811286
  0.48655394 0.69566

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
M = (np.random.rand(10)*100).astype(np.float32)
Y = M.view(np.int32)
Y[:] = M
print(Y)

[83 35 28 72 31 53 23 82  0 47]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
M = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(M)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if __name__ == '__main__':


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
M = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(M):
    print(index, value)
for index in np.ndindex(M.shape):
    print(index, M[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
M = np.zeros((n,n))
np.put(M, np.random.choice(range(n*n), p, replace=False),1)
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.12499786  0.08176922 -0.09698337 -0.04965677  0.61210913  0.0922212
  -0.26300239 -0.25946001  0.32090594 -0.31290509]
 [-0.16453139  0.14219436 -0.31473509  0.14751564 -0.09456036  0.22165238
   0.03447368 -0.4660178   0.23444293  0.25956564]
 [-0.07499725 -0.3379655  -0.36661724  0.1063809  -0.03791026  0.23998706
   0.32275159 -0.01811716  0.4797122  -0.31322434]
 [ 0.28553939 -0.06610784 -0.44200994 -0.48677506  0.12778557 -0.06775147
  -0.13431534  0.41593939 -0.11605163  0.48374691]
 [-0.33782605  0.48596422 -0.36242097 -0.06305117 -0.18121672 -0.31164523
  -0.25910952  0.39367218  0.20216683  0.43346643]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
M = np.random.randint(0,10,(3,3))
print(M)
print(M[M[:,1].argsort()])

[[5 1 0]
 [1 8 4]
 [0 8 4]]
[[5 1 0]
 [1 8 4]
 [0 8 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
# null : np.nan
M=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(M).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
M = np.random.uniform(0,1,10)
p = 0.5
m = M.flat[np.abs(M - p).argmin()]
print(m)

0.46331292825222037


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

M = NamedArray(np.arange(5), "R5")
print (M.name)

R5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
M = np.ones(10)
I = np.random.randint(0,len(M),20)
M += np.bincount(I, minlength=len(M))
print(M)

# better solution from forum
np.add.at(M, I, 1)
print(M)

[2. 3. 1. 3. 4. 4. 4. 3. 4. 2.]
[3. 5. 1. 5. 7. 7. 7. 5. 7. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)


[[48 60 54 54]
 [44 52 59 58]
 [35 66 58 36]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.60866666 0.52641358 0.57589604 0.57269161 0.52488494 0.66045491
 0.52928725 0.42622129 0.41288972 0.46774959]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.74199017, 1.09743527, 1.54072891, 1.27428047, 2.02026376])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
M = np.array([1,2,3,4,5])
nz = 3
M0 = np.zeros(len(M) + (len(M)-1)*(nz))
M0[::nz+1] = M
print(M0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 65) ( 0, 88) ( 4, 38) ( 4, 41) ( 5, 48) ( 5, 62) ( 6, 26) ( 6, 29)
 ( 6, 38) ( 6, 93) ( 7, 64) ( 7, 78) (14, 33) (14, 65) (16, 27) (16, 43)
 (26, 29) (27, 43) (28, 37) (28, 79) (33, 65) (37, 79) (38, 41) (38, 93)
 (48, 62) (64, 78) (65, 88) (88, 94) (88, 97) (94, 97)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
M = np.arange(20)
print(moving_average(M, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def fff(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
M = fff(np.arange(10), 3)
print(M)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
M = np.random.randint(0,2,100)
np.logical_not(M, out=M)

M = np.random.uniform(-1.0,1.0,100)
np.negative(M, out=M)

array([ 0.91162705, -0.74450047, -0.00504292,  0.10055869,  0.54357139,
       -0.43721625,  0.52474251,  0.92510363, -0.96741246, -0.91193647,
        0.63924987,  0.35448682,  0.14429912,  0.71831435,  0.16343047,
       -0.50392507,  0.65335525,  0.7354361 , -0.30576782, -0.79273   ,
        0.9066817 ,  0.3646706 , -0.01204349,  0.8274931 , -0.93336967,
        0.118387  ,  0.01038812,  0.75524058,  0.98474359,  0.86769826,
        0.9046238 ,  0.31923502,  0.12211142, -0.29273124, -0.39596036,
        0.18538327,  0.75830359, -0.78362936,  0.79501968, -0.35132408,
        0.240626  ,  0.72138922, -0.34346115,  0.9481094 ,  0.88492004,
       -0.18168827, -0.37878999,  0.05088919,  0.61101383,  0.8464893 ,
        0.42570496,  0.33456479, -0.86361937, -0.22747177, -0.86916223,
        0.23002687, -0.55497107,  0.08053664, -0.64820113,  0.71422189,
        0.0675007 , -0.06162563,  0.91526467,  0.5206881 , -0.87729196,
        0.0025626 , -0.47860592,  0.36156837, -0.48319469,  0.47

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[8.79556497 3.80644613 9.84436626 0.48494054 0.13815201 2.55784563
 2.93633786 7.8571696  0.83863562 2.4120631 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# distance function from prev task used
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.20789095  5.11836267 13.34385824  5.1493485   2.88898615  6.03855753
   5.69677239  3.5351084   2.68707233  4.05344099]
 [ 4.14432953  2.39897483  2.25678039  5.91853565  1.83004498  5.51045308
   3.46494211  6.01070819  5.57189081  7.15070278]
 [ 8.69804632  6.79025833  8.41538466  4.88284369  8.52078679  1.5352766
   5.0256887   3.61023901  4.10663886  5.68329065]
 [10.29587788  8.29001407 12.59785529  3.29482426 11.45323465  1.58660597
  10.20328131  8.71717478  9.28205124  3.86368839]
 [ 1.55228107  0.46188497 16.52883008  4.26145065  3.16413993  7.41492458
  11.03492904  3.73650122  4.56705531  3.48794816]
 [ 0.08429899  1.92345217 16.80455205  5.29731058  1.66131002  8.06516745
  10.7566818   2.57123094  3.43721451  4.47422536]
 [11.3588476   9.55208275  2.37225393 10.11851974  9.64120943  7.44979289
   0.49829434  0.97537601  1.27518729 11.04874126]
 [12.99884037 11.11894193  5.3103676   9.30927334 12.25915222  5.4029224
   3.3426837   5.05697351  5.39471882 10.05547963]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
M = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=M.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Ms = np.array(list(M.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
M_start = (P-Rs//2)
M_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(M_start,0)).tolist()
M_start = (np.maximum(M_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(M_stop-Ms,0))).tolist()
M_stop = (np.minimum(M_stop,Ms)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(M_start,M_stop)]
R[r] = M[z]
print(M)
print(R)

[[4 9 7 0 3 1 7 8 6 4]
 [0 0 6 6 1 9 0 8 0 3]
 [4 8 1 6 0 3 3 2 9 8]
 [1 8 5 4 8 6 9 1 4 2]
 [5 4 0 5 0 6 9 5 2 7]
 [2 0 0 8 7 7 3 4 1 6]
 [6 7 0 8 1 3 8 7 2 4]
 [1 3 8 4 7 8 8 8 1 8]
 [5 9 5 0 7 4 3 1 1 1]
 [0 8 5 9 2 9 8 6 0 7]]
[[0 0 0 0 0]
 [0 4 9 7 0]
 [0 0 0 6 6]
 [0 4 8 1 6]
 [0 1 8 5 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
M = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(M,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
M = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(M) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
M = np.random.randint(0,10,50)
print(np.bincount(M).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
M = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (M.shape[0]-3)
j = 1 + (M.shape[1]-3)
C = stride_tricks.as_strided(M, shape=(i, j, n, n), strides=M.strides + M.strides)
print(C)

M = np.random.randint(0,5,(10,10))
print(sliding_window_view(M, window_shape=(3, 3)))

[[[[0 1 0]
   [2 4 0]
   [3 2 1]]

  [[1 0 0]
   [4 0 0]
   [2 1 2]]

  [[0 0 1]
   [0 0 2]
   [1 2 1]]

  [[0 1 4]
   [0 2 3]
   [2 1 4]]

  [[1 4 2]
   [2 3 2]
   [1 4 0]]

  [[4 2 3]
   [3 2 0]
   [4 0 3]]

  [[2 3 4]
   [2 0 1]
   [0 3 0]]

  [[3 4 3]
   [0 1 4]
   [3 0 2]]]


 [[[2 4 0]
   [3 2 1]
   [3 1 4]]

  [[4 0 0]
   [2 1 2]
   [1 4 2]]

  [[0 0 2]
   [1 2 1]
   [4 2 4]]

  [[0 2 3]
   [2 1 4]
   [2 4 2]]

  [[2 3 2]
   [1 4 0]
   [4 2 0]]

  [[3 2 0]
   [4 0 3]
   [2 0 1]]

  [[2 0 1]
   [0 3 0]
   [0 1 4]]

  [[0 1 4]
   [3 0 2]
   [1 4 4]]]


 [[[3 2 1]
   [3 1 4]
   [3 4 0]]

  [[2 1 2]
   [1 4 2]
   [4 0 1]]

  [[1 2 1]
   [4 2 4]
   [0 1 2]]

  [[2 1 4]
   [2 4 2]
   [1 2 4]]

  [[1 4 0]
   [4 2 0]
   [2 4 3]]

  [[4 0 3]
   [2 0 1]
   [4 3 3]]

  [[0 3 0]
   [0 1 4]
   [3 3 2]]

  [[3 0 2]
   [1 4 4]
   [3 2 4]]]


 [[[3 1 4]
   [3 4 0]
   [1 4 0]]

  [[1 4 2]
   [4 0 1]
   [4 0 0]]

  [[4 2 4]
   [0 1 2]
   [0 0 4]]

  [[2 4 2]
   [1 2 4]
   [0 4 2]]

  [[4 2 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def sym(M):
    return np.asarray(M + M.T - np.diag(M.diagonal())).view(Sym)

S = sym(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 12  9 12 10]
 [12  6 10 13 10]
 [ 9 10  9 42 17]
 [12 13 42  0  9]
 [10 10 17  9  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]]) # Compute tensor dot product along specified axes.
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
M = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(M, np.arange(0, M.shape[0], k), axis=0),
                                       np.arange(0, M.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(M):
    # Count neighbours
    N = (M[0:-2,0:-2] + M[0:-2,1:-1] + M[0:-2,2:] +
         M[1:-1,0:-2]                + M[1:-1,2:] +
         M[2:  ,0:-2] + M[2:  ,1:-1] + M[2:  ,2:])

    # Apply rules
    birth = (N==3) & (M[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (M[1:-1,1:-1]==1)
    M[...] = 0
    M[1:-1,1:-1][birth | survive] = 1
    return M

M = np.random.randint(0,2,(50,50))
for i in range(100): M = iterate(M)
print(M)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
M = np.arange(10000)
np.random.shuffle(M)
n = 5

# Fast method from forum
print (M[np.argpartition(-M,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
M = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(M.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.81 s ± 111 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
138 ms ± 587 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
126 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
M = np.random.randint(0,5,(10,3))
print(M)
# soluiton from forum for numerical arrays only, will work for any number of columns in M
U = M[M.max(axis=1) != M.min(axis=1),:]
print(U)

[[4 1 4]
 [2 3 4]
 [2 2 4]
 [0 0 4]
 [3 0 4]
 [3 0 1]
 [0 0 4]
 [1 2 2]
 [4 3 1]
 [4 0 2]]
[[4 1 4]
 [2 3 4]
 [2 2 4]
 [0 0 4]
 [3 0 4]
 [3 0 1]
 [0 0 4]
 [1 2 2]
 [4 3 1]
 [4 0 2]]
[[4 1 4]
 [2 3 4]
 [2 2 4]
 [0 0 4]
 [3 0 4]
 [3 0 1]
 [0 0 4]
 [1 2 2]
 [4 3 1]
 [4 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
M = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(M).view(np.dtype((np.void, M.dtype.itemsize * M.shape[1])))
_, idx = np.unique(T, return_index=True)
uM = M[idx]
print(uM)

[[1 0 0]
 [1 0 1]
 [1 1 1]]
[[1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[3.96514810e-01, 3.88892141e-01, 3.46348156e-01, 7.22277526e-02,
        1.54551479e-01, 4.21404916e-01, 3.88524595e-01, 1.87219868e-01,
        6.10360241e-03, 1.52851002e-02],
       [5.84429705e-02, 5.73194529e-02, 5.10488249e-02, 1.06457674e-02,
        2.27795969e-02, 6.21115643e-02, 5.72652797e-02, 2.75946446e-02,
        8.99620007e-04, 2.25289609e-03],
       [3.02535455e-01, 2.96719462e-01, 2.64258975e-01, 5.51088017e-02,
        1.17920695e-01, 3.21526271e-01, 2.96439029e-01, 1.42846236e-01,
        4.65696637e-03, 1.16623255e-02],
       [1.58602172e-01, 1.55553177e-01, 1.38535985e-01, 2.88904177e-02,
        6.18191292e-02, 1.68557980e-01, 1.55406162e-01, 7.48861759e-02,
        2.44138322e-03, 6.11389548e-03],
       [5.96037897e-01, 5.84579563e-01, 5.20627784e-01, 1.08572181e-01,
        2.32320549e-01, 6.33452507e-01, 5.84027071e-01, 2.81427412e-01,
        9.17488643e-03, 2.29764407e-02],
       [2.52448875e-01, 2.47595755e-01, 2.20509298e-01, 4.59852053e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n) # the bit-wise AND
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.08864022  0.2943639 ]
