# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
null_vector.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vec6 = np.zeros(10)
vec6[4] = 1
vec6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec7 = np.arange(10, 50)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.flip(vec7)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix9 = np.matrix(np.arange(0, 9).reshape(3, 3))
matrix9

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr10 = [1,2,0,0,4,0]
for i in range(0, len(arr10)):
  if arr10[i] == 0:
    print(f'index of 0 is {i}')

index of 0 is 2
index of 0 is 3
index of 0 is 5


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
m11 = np.identity(3)
print(m11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
m12 = np.random.rand(3, 3, 3)
m12

array([[[0.41913343, 0.32163887, 0.97407029],
        [0.96870275, 0.58514921, 0.01420992],
        [0.81105194, 0.44634539, 0.34825155]],

       [[0.74949147, 0.62592922, 0.18184004],
        [0.60376688, 0.45395629, 0.27237117],
        [0.56401406, 0.94208041, 0.62021685]],

       [[0.69211343, 0.39722872, 0.86194947],
        [0.40735808, 0.41484614, 0.83976706],
        [0.03018822, 0.7553661 , 0.60789459]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a13 = np.random.rand(10, 10)
a13.max(), a13.min()

(0.9978874197467251, 0.011907352266608107)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
v14 = np.random.rand(30)
v14.mean()

0.4577109601161765

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a15 = np.ones((5,5))
a15[1:-1,1:-1] = 0
a15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
p16 = np.ones((4, 6)) # any array
a16 = np.zeros((p16.shape[0]+2,p16.shape[1]+2))
a16[1:-1,1:-1] = p16
a16

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
# print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)
0.1 * 3

nan
False
False
nan
False


0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
m18 = np.zeros([5, 5])
j=1;k=1
for i in range(1,5):
  m18[i,j-1] = k  
  j=j+1;k+=1
m18

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
a=np.ones((6,7,8))
m=0
for i in range(6):
  for j in range (7):
    for k in range(8):
      if(m==100):
       break
      m=m+1
print(i,j,k)

5 6 0


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
A = np.array([[[[[[[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]]]]]]])
x = np.tile(A,reps=4)
print(x)

[[[[[[[[0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]]]]]]]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.random.rand(5,5)
min=np.min(a);max=np.max(a)
a=(a-min)/(max-min)
a

array([[0.56206774, 0.10421327, 0.42180732, 0.04522447, 0.50560601],
       [0.28876313, 0.95391614, 0.19227068, 0.10574008, 0.76946423],
       [0.81500863, 0.63247556, 0.68210816, 0.33991816, 0.14497516],
       [0.67011953, 0.        , 1.        , 0.84090749, 0.49308323],
       [0.82925253, 0.97928748, 0.46584678, 0.14478349, 0.04546904]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
my_type = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
testt = np.array((1, 2, 3, 4), dtype=my_type)
print(my_type['R'])
testt

uint8


array((1, 2, 3, 4),
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.random.rand(5,3)
b=np.random.rand(3,2)
np.matmul(a,b)

array([[0.57383771, 0.76048882],
       [0.09521471, 0.55561627],
       [0.57744851, 1.15972191],
       [0.5942069 , 0.8284286 ],
       [0.62537976, 1.42986524]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.random.randint(1,10,size=(20,))
for i in range(20):
  if (3<a[i])&(a[i]<8) :
    a[i]*=-1
a

array([ 2, -4,  8,  2, -7,  8, -4,  8,  9, -4,  8,  9,  3,  2,  9, -5, -7,
       -7,  8, -6])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
q = np.array([1, 2, 3])
q**q, 2 << q >> 2, q <- q, q/1/1

(array([ 1,  4, 27]),
 array([1, 2, 4]),
 array([False, False, False]),
 array([1., 2., 3.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Q = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Q)), Q))

[ 1.  7.  3. -6. -2. -1. -5. -3. -7. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2022-11-30'),
 numpy.datetime64('2022-12-01'),
 numpy.datetime64('2022-12-02'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
E = np.random.uniform(0,10,10)

print(E - E%1)
print(E // 1)
print(np.floor(E))
print(E.astype(int))
print(np.trunc(E))

[6. 1. 6. 4. 7. 0. 1. 1. 3. 7.]
[6. 1. 6. 4. 7. 0. 1. 1. 3. 7.]
[6. 1. 6. 4. 7. 0. 1. 1. 3. 7.]
[6 1 6 4 7 0 1 1 3 7]
[6. 1. 6. 4. 7. 0. 1. 1. 3. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
E = np.zeros((5,5))
E += np.arange(5)
print(E)

# without broadcasting
E = np.tile(np.arange(0, 5), (5,1))
print(E)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for x in range(10):
        yield x
E = np.fromiter(generate(),dtype=float,count=-1)
print(E)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
E = np.linspace(0,1,11,endpoint=False)[1:]
print(E)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
E = np.random.random(10)
E.sort()
print(E)

[0.03467393 0.11611624 0.1777707  0.20863901 0.28262856 0.44740488
 0.58032402 0.74134497 0.98111476 0.99194072]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
E = np.arange(10)
np.add.reduce(E)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [85]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
M = np.zeros(10)
M.flags.writeable = False
# M[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
M = np.random.random((10,2))
X,Y = M[:,0], M[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.73234185 1.05628888 0.95934589 0.89974711 0.8218724  1.05347092
 1.24175229 0.92878109 0.5401229  0.81147314]
[0.39253386 1.19328402 0.67891826 0.95334765 0.36315288 0.41521824
 0.85551391 0.17109084 1.40275775 0.59345505]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
M = np.random.random(10)
M[M.argmax()] = 0
print(M)

[0.10368094 0.         0.30634181 0.57293117 0.42536763 0.50302509
 0.55055597 0.31681624 0.09192117 0.03830102]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
M = np.zeros((5,5), [('x',float),('y',float)])
M['x'], M['y'] = np.meshgrid(np.linspace(0,1,5), # Return coordinate matrices from coordinate vectors.
                             np.linspace(0,1,5))
print(M)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
np.set_printoptions(threshold=float("inf"))
M = np.zeros((40,40))
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
M = np.arange(100)
v = np.random.uniform(0,100) # Draw samples from a uniform distribution.
index = (np.abs(M-v)).argmin()
print(M[index])

41


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [86]:
M = np.zeros(2, [('position', 
                   [('x', float, 1), ('y', float, 1)]), 
                  ('color', [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(M)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
M = np.random.random((10,2))
X,Y = np.atleast_2d(M[:,0], M[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.3620674  0.32017688 0.67590147 0.46451002 0.87056508
  0.32948906 0.67077501 0.67041628 0.48793563]
 [0.3620674  0.         0.0452894  0.55064982 0.42014641 0.85358347
  0.58372328 0.79428959 0.7223805  0.58487717]
 [0.32017688 0.0452894  0.         0.57069434 0.42521439 0.86371841
  0.5567802  0.78618408 0.72225493 0.57655198]
 [0.67590147 0.55064982 0.57069434 0.         0.21729745 0.33888353
  0.58906673 0.4767439  0.33286521 0.36135536]
 [0.46451002 0.42014641 0.42521439 0.21729745 0.         0.44159443
  0.38846731 0.40446716 0.3065282  0.21568515]
 [0.87056508 0.85358347 0.86371841 0.33888353 0.44159443 0.
  0.65246293 0.33883213 0.22546408 0.40025278]
 [0.32948906 0.58372328 0.5567802  0.58906673 0.38846731 0.65246293
  0.         0.37548954 0.42826136 0.25823611]
 [0.67077501 0.79428959 0.78618408 0.4767439  0.40446716 0.33883213
  0.37548954 0.         0.14995624 0.20966219]
 [0.67041628 0.7223805  0.72225493 0.33286521 0.3065282  0.22546408
  0.42826136 0.14995

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
M = (np.random.rand(10)*100).astype(np.float32)
Y = M.view(np.int32)
Y[:] = M
print(Y)

[13 89 95 73 64 19 59 57 41 31]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO

# fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
M = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(M)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if __name__ == '__main__':


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
M = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(M):
    print(index, value)
for index in np.ndindex(M.shape):
    print(index, M[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
n = 10
p = 3
M = np.zeros((n,n))
np.put(M, np.random.choice(range(n*n), p, replace=False),1)
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.07995197 -0.09501416 -0.41486654  0.20970329  0.23346137  0.26142631
   0.03394794 -0.02030902 -0.06613199 -0.06226523]
 [ 0.28553991 -0.27548674 -0.09666518  0.00175121 -0.08101391  0.43031181
  -0.08553316 -0.09017681 -0.18348171  0.09475458]
 [-0.09122175 -0.32415005  0.15628846 -0.22069283  0.05289852  0.07393114
   0.13760325  0.16682617  0.44443484 -0.39591774]
 [-0.0519181   0.01453632 -0.14783967  0.28570903 -0.42685881  0.38094043
  -0.39734445  0.18073019 -0.02901982  0.19106489]
 [ 0.17009496  0.37617973  0.00190293 -0.0191475  -0.347796    0.45145624
   0.07678858 -0.24156191 -0.23661967 -0.23129736]]


#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
M = np.random.randint(0,10,(3,3))
print(M)
print(M[M[:,1].argsort()])

[[8 3 3]
 [0 0 9]
 [2 7 9]]
[[0 0 9]
 [8 3 3]
 [2 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
# null : np.nan
M=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(M).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
M = np.random.uniform(0,1,10)
p = 0.5
m = M.flat[np.abs(M - p).argmin()]
print(m)

0.5488363278968234


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

M = NamedArray(np.arange(5), "R5")
print (M.name)

R5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
M = np.ones(10)
I = np.random.randint(0,len(M),20)
M += np.bincount(I, minlength=len(M))
print(M)

# better solution from forum
np.add.at(M, I, 1)
print(M)

[1. 3. 2. 4. 5. 2. 2. 5. 2. 4.]
[1. 5. 3. 7. 9. 3. 3. 9. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [66]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)


[[54 70 29 56]
 [54 65 52 38]
 [40 67 58 33]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.5697603  0.39519709 0.63482371 0.46364733 0.46250956 0.5410659
 0.74601119 0.51380046 0.41765749 0.49904124]


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.41197123, 1.2530682 , 2.79034476, 1.21320265, 1.29648051])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
M = np.array([1,2,3,4,5])
nz = 3
M0 = np.zeros(len(M) + (len(M)-1)*(nz))
M0[::nz+1] = M
print(M0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [71]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 56) ( 1, 72) ( 1, 86) ( 1, 97) ( 4,  6) ( 4, 28) ( 6, 28) (10, 17)
 (10, 53) (17, 30) (17, 53) (17, 93) (18, 32) (18, 38) (30, 93) (32, 38)
 (32, 52) (32, 61) (37, 55) (37, 74) (51, 56) (51, 99) (52, 61) (55, 74)
 (56, 97) (56, 99) (71, 82) (72, 86) (82, 82)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [75]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
M = np.arange(20)
print(moving_average(M, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [76]:
from numpy.lib import stride_tricks

def fff(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
M = fff(np.arange(10), 3)
print(M)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
M = np.random.randint(0,2,100)
np.logical_not(M, out=M)

M = np.random.uniform(-1.0,1.0,100)
np.negative(M, out=M)

array([ 0.08820597,  0.12220594, -0.4482249 ,  0.74886735,  0.53800727,
        0.94894183,  0.81706839,  0.67544827,  0.96949316, -0.62361823,
       -0.44594162, -0.58598825, -0.386571  , -0.8011294 ,  0.92732308,
       -0.07955974, -0.5881678 , -0.57474257,  0.87729177,  0.79306258,
        0.02110316, -0.44311425, -0.78992154, -0.38241744,  0.69884857,
        0.18949835,  0.56709243, -0.64342615, -0.75647016,  0.39154657,
        0.58868877,  0.02438242, -0.28230915, -0.1097449 , -0.38233474,
        0.02711488, -0.9456049 ,  0.15108439, -0.45310793,  0.44023305,
        0.1107465 , -0.19241272,  0.82594103,  0.45396414,  0.30200439,
        0.6626963 ,  0.58345223,  0.83717771, -0.49530537,  0.70382645,
       -0.17397483,  0.06687114,  0.96211511, -0.96897827,  0.54904245,
       -0.68292393,  0.9617422 , -0.6727112 ,  0.59536292,  0.54715255,
        0.67619655,  0.42863842,  0.81302858, -0.3876648 ,  0.33527389,
       -0.33830342,  0.1422325 , -0.38642985,  0.81337851,  0.48

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[4.93186295 1.86851173 2.24855323 6.67996027 1.73752401 1.8979692
 1.16707493 3.85700314 0.2560289  2.04480908]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [79]:
# distance function from prev task used
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[6.87811128e+00 6.78189420e+00 7.21753051e+00 1.45900259e+01
  5.36892205e+00 3.37390201e+00 5.46869880e+00 1.57618564e+01
  5.15242069e+00 1.00136646e+01]
 [8.33863990e+00 1.01660312e+01 1.17404829e+01 2.61117508e-01
  7.47143394e+00 1.45801596e+01 1.03831210e+01 9.41588379e-01
  1.17880243e+01 3.95953062e+00]
 [5.31149533e+00 4.95856802e+00 3.15208923e-01 1.38003632e+01
  1.49521771e+01 7.79030754e+00 1.60949763e+01 1.23654162e+01
  1.44849706e+00 9.56403413e+00]
 [8.53863606e+00 9.00131583e+00 6.20540182e+00 8.15057515e+00
  1.34685801e+01 1.23840736e+01 1.55031694e+01 6.38415854e+00
  4.55428943e+00 3.97622994e+00]
 [4.04383762e+00 3.96143236e+00 5.08825702e+00 1.38788223e+01
  7.20728390e+00 6.19200967e-01 7.60928051e+00 1.44793164e+01
  3.80419221e+00 9.37880488e+00]
 [5.90637041e-01 7.89122557e-01 2.98473071e+00 5.36117489e+00
  3.79287504e+00 5.04065443e+00 5.42886508e+00 5.76994483e+00
  4.90101047e+00 9.14743708e-01]
 [1.10712432e+01 1.28618895e+01 1.36957030e+01 2.88172832e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [80]:
M = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=M.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Ms = np.array(list(M.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
M_start = (P-Rs//2)
M_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(M_start,0)).tolist()
M_start = (np.maximum(M_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(M_stop-Ms,0))).tolist()
M_stop = (np.minimum(M_stop,Ms)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(M_start,M_stop)]
R[r] = M[z]
print(M)
print(R)

[[4 2 3 6 5 5 9 5 2 6]
 [1 9 5 4 9 5 1 7 5 6]
 [7 8 7 2 9 8 4 7 1 2]
 [5 7 2 1 2 4 8 9 9 8]
 [8 6 4 8 3 7 0 1 1 8]
 [7 8 9 3 2 9 0 5 6 7]
 [6 4 7 7 8 8 5 8 9 7]
 [5 1 4 6 3 5 2 8 3 1]
 [0 5 0 0 7 9 1 2 7 1]
 [8 0 5 4 5 9 1 0 4 4]]
[[0 0 0 0 0]
 [0 4 2 3 6]
 [0 1 9 5 4]
 [0 7 8 7 2]
 [0 5 7 2 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [81]:
M = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(M,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [82]:
M = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(M) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [83]:
M = np.random.randint(0,10,50)
print(np.bincount(M).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
M = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (M.shape[0]-3)
j = 1 + (M.shape[1]-3)
C = stride_tricks.as_strided(M, shape=(i, j, n, n), strides=M.strides + M.strides)
print(C)

M = np.random.randint(0,5,(10,10))
print(sliding_window_view(M, window_shape=(3, 3)))

[[[[4 2 2]
   [0 4 2]
   [0 4 0]]

  [[2 2 4]
   [4 2 0]
   [4 0 0]]

  [[2 4 4]
   [2 0 0]
   [0 0 2]]

  [[4 4 1]
   [0 0 0]
   [0 2 4]]

  [[4 1 1]
   [0 0 1]
   [2 4 0]]

  [[1 1 4]
   [0 1 1]
   [4 0 2]]

  [[1 4 0]
   [1 1 3]
   [0 2 1]]

  [[4 0 4]
   [1 3 0]
   [2 1 4]]]


 [[[0 4 2]
   [0 4 0]
   [1 4 1]]

  [[4 2 0]
   [4 0 0]
   [4 1 4]]

  [[2 0 0]
   [0 0 2]
   [1 4 3]]

  [[0 0 0]
   [0 2 4]
   [4 3 3]]

  [[0 0 1]
   [2 4 0]
   [3 3 4]]

  [[0 1 1]
   [4 0 2]
   [3 4 4]]

  [[1 1 3]
   [0 2 1]
   [4 4 4]]

  [[1 3 0]
   [2 1 4]
   [4 4 1]]]


 [[[0 4 0]
   [1 4 1]
   [0 2 3]]

  [[4 0 0]
   [4 1 4]
   [2 3 4]]

  [[0 0 2]
   [1 4 3]
   [3 4 3]]

  [[0 2 4]
   [4 3 3]
   [4 3 0]]

  [[2 4 0]
   [3 3 4]
   [3 0 2]]

  [[4 0 2]
   [3 4 4]
   [0 2 4]]

  [[0 2 1]
   [4 4 4]
   [2 4 2]]

  [[2 1 4]
   [4 4 1]
   [4 2 1]]]


 [[[1 4 1]
   [0 2 3]
   [1 1 1]]

  [[4 1 4]
   [2 3 4]
   [1 1 4]]

  [[1 4 3]
   [3 4 3]
   [1 4 4]]

  [[4 3 3]
   [4 3 0]
   [4 4 2]]

  [[3 3 4]
   

NameError: ignored

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Sym, self).__setitem__((i,j), value)
        super(Sym, self).__setitem__((j,i), value)

def sym(M):
    return np.asarray(M + M.T - np.diag(M.diagonal())).view(Sym)

S = sym(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]]) # Compute tensor dot product along specified axes.
print(S)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
M = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(M, np.arange(0, M.shape[0], k), axis=0),
                                       np.arange(0, M.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(M):
    # Count neighbours
    N = (M[0:-2,0:-2] + M[0:-2,1:-1] + M[0:-2,2:] +
         M[1:-1,0:-2]                + M[1:-1,2:] +
         M[2:  ,0:-2] + M[2:  ,1:-1] + M[2:  ,2:])

    # Apply rules
    birth = (N==3) & (M[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (M[1:-1,1:-1]==1)
    M[...] = 0
    M[1:-1,1:-1][birth | survive] = 1
    return M

M = np.random.randint(0,2,(50,50))
for i in range(100): M = iterate(M)
print(M)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
M = np.arange(10000)
np.random.shuffle(M)
n = 5

# Fast method from forum
print (M[np.argpartition(-M,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
M = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(M.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
M = np.random.randint(0,5,(10,3))
print(M)
# soluiton from forum for numerical arrays only, will work for any number of columns in M
U = M[M.max(axis=1) != M.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
M = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(M).view(np.dtype((np.void, M.dtype.itemsize * M.shape[1])))
_, idx = np.unique(T, return_index=True)
uM = M[idx]
print(uM)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n) # the bit-wise AND
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)